// src/components/actions/Slidenav.tsx
import { For } from "solid-js";
import { dotStyles } from "@/components/actions/styles";
import { setVideoPlaying } from "@/frontend/stores";

type Props = {
	idx: number;
	setIdx: (value: number) => void;
	length: number;
	class?: string;
};

export default function Slidenav(props: Props) {
	return (
		<For each={Array(props.length)}>
			{(_, i) => (
				<button
					onclick={() => {
						setVideoPlaying(false);
						props.setIdx(i());
					}}
					aria-label={`View slide ${i() + 1}`}
					class="cursor-pointer touch-manipulation p-2"
					tabindex="0"
				>
					<div class={dotStyles({ open: props.idx === i() })}></div>
				</button>
			)}
		</For>
	);
}

// src/components/interact/Slidenav.svelte
<script lang="ts">
  import type { VariantProps } from "class-variance-authority";
  import { nav } from "@actions/meta";

  let {
    idx = $bindable(0),
    class: className,
    length,
    variant = {},
  }: {
    idx: number;
    class?: string;
    length: number;
    variant?: VariantProps<typeof nav>;
  } = $props();
</script>

<div class="relative {className}">
  {#each Array(length) as _, i}
    <button
      onclick={() => (idx = i)}
      aria-label="View slide {i}"
      class={nav({ ...variant, state: idx === i })}
      tabindex="0"
    ></button>
  {/each}
</div>
