// src/components/interact/Slideshow.tsx
import { For, createSignal } from "solid-js";

export type SlideshowMeta = {
  active: string,
  hidden: string,
  base: string,
  images: any[],
}

export default function Slideshow(props: { class: string; meta: SlideshowMeta }) {
  const [activeIndex, setActiveIndex] = createSignal(0);

  return (
    <div class={props.class}>
      <For each={props.meta.images}>
        {(image, i) => (
          <img
            class={
              `object-cover ${props.meta.base} ${activeIndex() === i() ? props.meta.active : props.meta.hidden
              }`}
            {...image}
            data-index={i()}
          />
        )}
      </For>
    </div>
  );
}

// src/components/interact/Slideshow.svelte
<script lang="ts">
  type SlideshowMeta = {
    active: string;
    hidden: string;
    base: string;
    images: any[];
  };

  const {
    idx = $bindable(0),
    class: className,
    meta,
  }: {
    idx?: number;
    class: string;
    meta: SlideshowMeta;
  } = $props();
</script>

<div class={className}>
  {#each meta.images as image, i}
    <img
      class={`object-cover ${meta.base} ${idx === i ? meta.active : meta.hidden}`}
      {...image}
      data-index={i}
      widths={[750, 1300, 2160]}
      sizes="60vw"
      width={2160}
      draggable={false}
    />
  {/each}
</div>
