// src/components/sections/TextCarousel.tsx
import { For, onCleanup, onMount } from 'solid-js';
import Star from '~icons/ph/star-four-fill';
import type { Props as TextCarouselMeta } from './TextCarousel.astro';

export default function TextCarousel(props: TextCarouselMeta) {
	let textCarousel!: HTMLElement;
	let container!: HTMLElement;

	let clientX = 0;
	let clientY = 0;
	let startPos = 0;
	let rawPos = 0;
	let moveDirection = -1;
	let lastFrame = 0;

	let pos = 0;
	let isVisible = false;
	let animationId: number | null = null;
	let pointerId: number | null = null;

	let currentVelocity = 0;
	let prevX = 0;

	const updateTranslation = (o: number) => {
		const w = (textCarousel.children[0] as HTMLElement).scrollWidth;
		pos = o - Math.floor(o / w) * w;
		textCarousel.style.translate = `${-pos}px 0 0`;
	};

	const scrollMultiplier = (e: HTMLElement) => window.innerWidth / e.getBoundingClientRect().width;

	const animate = (currentTime: number = 0) => {
		if (!isVisible) return;
		const friction = 0.9;
		const dt = currentTime - lastFrame;
		lastFrame = currentTime;

		const movement = currentVelocity * (dt / 16);
		rawPos += moveDirection * props.speed * dt + movement;
		currentVelocity *= Math.pow(friction, dt / 16);

		updateTranslation(rawPos);
		animationId = requestAnimationFrame(animate);
	};

	onMount(() => {
		const observer = new IntersectionObserver(([entry]) => {
			if (entry && entry.isIntersecting !== isVisible) {
				isVisible = entry.isIntersecting;
				if (isVisible) {
					requestAnimationFrame(animate);
				} else if (animationId != null) {
					cancelAnimationFrame(animationId);
					animationId = null;
				}
			}
		});

		observer.observe(container);

		onCleanup(() => {
			observer.disconnect();
			if (animationId != null) {
				cancelAnimationFrame(animationId);
				animationId = null;
			}
		});
	});

	function onPointerDown(e: PointerEvent) {
		if (e.button !== 0) return;

		pointerId = e.pointerId;
		(e.currentTarget as HTMLElement).setPointerCapture(pointerId);

		if (animationId != null) {
			cancelAnimationFrame(animationId);
			animationId = null;
		}

		window.getSelection()?.removeAllRanges();
		clientX = e.clientX;
		clientY = e.clientY;

		currentVelocity = 0;
		startPos = pos;
	}

	function onPointerMove(e: PointerEvent) {
		if (e.pointerId !== pointerId) return;

		rawPos = startPos - (e.clientX - clientX);
		updateTranslation(rawPos);

		const now = performance.now();
		const dt = now - lastFrame;
		if (dt > 0) {
			currentVelocity = (prevX - e.clientX) / dt;
		}

		lastFrame = now;
		prevX = e.clientX;
	}

	function onPointerUp(e: PointerEvent) {
		if (e.pointerId !== pointerId) return;
		if (pointerId != null) {
			(e.currentTarget as HTMLElement).releasePointerCapture(pointerId);
		}
		pointerId = null;

		const diffX = clientX - e.clientX;
		const diffY = clientY - e.clientY;
		moveDirection = diffX < 0 ? -1 : 1;

		if (Math.abs(diffX) > 20 && Math.abs(diffX) > Math.abs(diffY)) {
			currentVelocity *= scrollMultiplier(container) * 25;
			lastFrame = performance.now();
			requestAnimationFrame(animate);
		}
	}

	return (
		<div
			class="border-accent py-inset touch-pan-y border-y-1 contain-paint"
			ref={(el) => (container = el)}
			onPointerDown={onPointerDown}
			onPointerMove={onPointerMove}
			onPointerUp={onPointerUp}
			role="marquee"
		>
			<div
				ref={(el) => (textCarousel = el)}
				class="flex h-20 will-change-transform select-none md:h-25"
				style={{ translate: `${-pos}px 0 0` }}
			>
				<For each={[0, 1, 2]}>
					{() => (
						<div class="flex flex-none items-center">
							<For each={props.text}>
								{(item) => (
									<>
										<h3 class="mx-12 flex-none font-serif text-2xl md:mx-20 md:text-3xl lg:mx-23">
											{item}
										</h3>

										<Star class="text-gold size-7 flex-none sm:size-9" />
									</>
								)}
							</For>
						</div>
					)}
				</For>
			</div>
		</div>
	);
}

// src/components/interactable/TextCarousel.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Icon from "@iconify/svelte";

  export let text = [
    "Made with love",
    "No scrape of dust left",
    "Absolutely revelatory",
    "Expert opinions",
  ];

  export let speed = 0.45;

  let carousel: HTMLElement;
  let autoDirection = 1;
  let currentSpeed = speed;
  let isDragging = false;
  let startX = 0;
  let dragOffset = 0;
  let rawOffset = 0;
  let lastXDiff = 0;

  const updateTranslation = () => {
    const halfWidth = carousel.scrollWidth / 2;
    carousel.style.transform = `translateX(-${((rawOffset % halfWidth) + halfWidth) % halfWidth}px)`;
  };

  const animate = () => {
    if (
      !isDragging &&
      carousel.getBoundingClientRect().top <= window.innerHeight &&
      carousel.getBoundingClientRect().bottom >= 0
    ) {
      rawOffset += autoDirection * currentSpeed;
      updateTranslation();
    }
    requestAnimationFrame(animate);
  };

  onMount(() => {
    animate();
    const pointerMove = (e: PointerEvent) => {
      if (isDragging) {
        lastXDiff = e.pageX - startX;
        rawOffset = dragOffset - lastXDiff;
        updateTranslation();
      }
    };
    const pointerUp = (_: PointerEvent) => {
      if (isDragging) {
        isDragging = false;
        currentSpeed = speed;
        autoDirection = lastXDiff > 0 ? -1 : 1;
      }
    };

    window.addEventListener("pointermove", pointerMove);
    window.addEventListener("pointerup", pointerUp);

    return () => {
      window.removeEventListener("pointermove", pointerMove);
      window.removeEventListener("pointerup", pointerUp);
    };
  });
</script>

<div class="border-accent border-y-1">
  <div
    class="py-inset contain-paint"
    on:pointerdown={(e) => {
      isDragging = true;
      currentSpeed = 0;
      startX = e.pageX;
      dragOffset = rawOffset;
    }}
    on:pointercancel={() => {
      isDragging = false;
      currentSpeed = speed;
    }}
  >
    <div
      bind:this={carousel}
      class="flex h-18 transform-gpu touch-pan-y items-center gap-12 will-change-transform select-none md:h-20 md:gap-20 lg:gap-25 xl:h-25"
    >
      {#each [...text, ...text] as item}
        <h4 class="flex-shrink-0 font-serif text-4xl">{item}</h4>
        <Icon
          icon="ph:star-four-fill"
          class="text-gold h-auto w-8 flex-shrink-0"
        />
      {/each}
    </div>
  </div>
</div>
