// src/components/interactable/Faq.svelte
<script context="module" lang="ts">
  import { writable } from "svelte/store";
  import { slide } from "svelte/transition";
  import { sineOut } from "svelte/easing";
  const prev = writable<HTMLElement | null>(null);
</script>

<script lang="ts">
  export let title;
  let button: HTMLElement;

  function toggleFaq() {
    $prev = $prev === button ? null : button;
  }

  function slideWithScroll(node: HTMLElement, { duration = 250 }) {
    const baseSlide = slide(node, { duration, easing: sineOut });
    return {
      ...baseSlide,
      tick: (_: number) => {
        const r = button.getBoundingClientRect();
        if ($prev === button && r.top < 0) {
          window.scrollTo({ top: window.scrollY + r.top });
        }
      },
    };
  }

  $: isActive = $prev === button;
</script>

<button bind:this={button} class="w-full cursor-pointer" on:click={toggleFaq}>
  <div class="flex items-center justify-between gap-4">
    <h3 class="font-serif text-2xl font-semibold">{title}</h3>
    <div
      class="expand relative h-6 w-6 flex-shrink-0 {isActive ? 'active' : ''}"
    ></div>
  </div>
  <div class="overflow-hidden" aria-hidden={!isActive}>
    {#if isActive}
      <div transition:slideWithScroll={{ duration: 350 }} class="mt-1">
        <slot />
      </div>
    {:else}{/if}
  </div>
</button>

<style lang="scss">
  .expand {
    &::before {
      content: "";
      position: absolute;
      top: 0;
      left: calc(50% - 1px);
      bottom: 0;
      width: 2px;
      background-color: var(--color-black);
      transform-origin: center;
      transition: transform 250ms;
    }
    &::after {
      content: "";
      position: absolute;
      left: 0;
      top: calc(50% - 1px);
      right: 0;
      height: 2px;
      background-color: var(--color-black);
      transform-origin: center;
    }
    &.active::before {
      transform: rotateZ(90deg);
    }
  }
</style>

// src/components/sections/Faq.tsx
import { For, Show, createSignal } from 'solid-js';
import type { Props as FaqMeta } from './Faq.astro';

export default function Faq(props: FaqMeta['content']) {
	const [active, setActive] = createSignal<number | null>(null);

	return (
		<>
			<style>
				{`
          .expand::before {
            content: "";
            position: absolute;
            top: 0;
            left: calc(50% - 1px);
            bottom: 0;
            width: 2px;
            background-color: var(--color-black);
            transform-origin: center;
            transition: transform 250ms;
          }
          .expand::after {
            content: "";
            position: absolute;
            left: 0;
            top: calc(50% - 1px);
            right: 0;
            height: 2px;
            background-color: var(--color-black);
            transform-origin: center;
          }
          .expand.open::before {
            transform: rotateZ(90deg);
          }
        `}
			</style>

			<div class="-mt-6">
				<For each={props}>
					{(faq, i) => {
						const open = () => i() === active();
						return (
							<button
								class="border-accent w-full cursor-pointer touch-manipulation border-t-1 py-8 first:border-t-0"
								onClick={() => {
									setActive(open() ? null : i());
									window.getSelection()?.removeAllRanges();
								}}
							>
								<div class="gap-inset flex items-center justify-between">
									<h3 class="heading-3xl">{faq.title}</h3>
									<div class={`expand relative size-6 gap-4 flex-none${open() ? ' open' : ''}`} />
								</div>

								<Show when={open()}>
									<div class="prose mt-3 mr-4 max-w-[110ch] font-sans" innerHTML={faq.desc} />
								</Show>
							</button>
						);
					}}
				</For>
			</div>
		</>
	);
}
