// src/components/sections/Hero.tsx
import { createSignal, For } from 'solid-js';
import Slidenav from '@/components/actions/Slidenav';
import FluidTalk from '@/components/decor/FluidTalk';
import { Image, imageWrapperStyles } from '@/components/Image';
import { slideshow } from '@/frontend/slideshow';
import type { Props as HeroMeta } from './Hero.astro';

export default function Hero(props: HeroMeta) {
	const [idx, setIdx] = createSignal(0);

	const ImageCarousel = () => (
		<For each={props.content}>
			{(image, i) => (
				<Image active={i() === idx()} anim="fade" image={image} widths={[400, 650, 1300]} />
			)}
		</For>
	);

	return (
		<div
			class="flex gap-6 py-20 sm:items-center sm:py-30 md:gap-8 xl:gap-11"
			ref={(el) =>
				slideshow(el, {
					idx: idx(),
					setIdx: setIdx,
					length: props.content.length,
					speed: props.speed,
				})
			}
		>
			<div class="hidden w-1/2 flex-none flex-col sm:flex 2xl:flex-row-reverse">
				<div class="h-[70vh] max-h-165 min-h-100 w-full rounded-sm contain-paint">
					<ImageCarousel />
				</div>

				<div class="2xl:w-diff mt-3 flex flex-shrink-0 items-center justify-center gap-2 2xl:mt-0 2xl:flex-col">
					<Slidenav idx={idx()} setIdx={setIdx} length={props.content.length} />
				</div>
			</div>

			<div>
				<h1 class="heading-6xl font-bold">{props.title}</h1>

				<div class="my-5 flex items-center gap-2 sm:hidden">
					<div
						class={`${imageWrapperStyles({
							pos: 'left',
							size: 'sm',
						})} flex-1`}
					>
						<ImageCarousel />
					</div>

					<div class="flex flex-col gap-2">
						<Slidenav idx={idx()} setIdx={setIdx} length={props.content.length} />
					</div>
				</div>

				<p class="desc-base mt-3">{props.desc}</p>

				<FluidTalk />
			</div>
		</div>
	);
}

// src/components/sections/Hero.svelte
<script lang="ts">
  import { modals } from "~/frontend/stores";
  import { headingStyles, descStyles, imageStyles } from "./styles";
  import Slidenav from "@actions/Slidenav.svelte";

  import { type PropsOf } from "./registry";
  import { actionStyles } from "@actions/styles";
  let { meta }: { meta: PropsOf<"Hero"> } = $props();
  let idx = $state(0);
</script>

{#snippet imageCarousel()}
  {#each meta.content as image, i}
    <img
      class={imageStyles({ anim: "grow", active: idx == i })}
      fetchpriority={i === idx ? "low" : "high"}
      alt={image.alt}
      {...image.meta}
    />
  {/each}
{/snippet}

<div
  class="hidden w-1/2 flex-none flex-col items-center gap-6 sm:flex 2xl:flex-row-reverse"
>
  <div
    class="flex h-[70vh] max-h-165 min-h-100 justify-evenly rounded-sm contain-paint"
  >
    {@render imageCarousel()}
  </div>

  <div class="gap-5 flex 2xl:flex-col">
    <Slidenav bind:idx length={meta.content.length}></Slidenav>
  </div>
</div>

<div class="relative">
  <h1 class={headingStyles({ size: "6xl" })}>
    {meta.title}
  </h1>

  <div class="my-5 flex items-center gap-5 sm:hidden">
    <div
      class="-ml-inset flex h-60 flex-1 justify-evenly contain-paint"
    >
      {@render imageCarousel()}
    </div>

    <div class="flex flex-col gap-5">
      <Slidenav bind:idx length={meta.content.length} />
    </div>
  </div>

  <p class="{descStyles({ size: 'base' })} mt-3">
    {meta.desc}
  </p>

  <div class="mt-9">
    <button class={actionStyles()} onclick={() => modals.open(modals.talk)}
      >Let's Talk</button
    >
  </div>
</div>
