// src/sections/Hero.tsx
import { createSignal, For } from 'solid-js';
import SlideNav from '@/components/SlideNav';
import Image, { imageRoundedVariants } from '@/components/Image';
import { slideshow } from '@/frontend/slideshow';
import type { Props as HeroMeta } from './Hero.astro';
import { cn } from '@/frontend/utils';

export default function ImageCarousel(props: { content: HeroMeta['content'] }) {
	const [idx, setIdx] = createSignal(0);
	slideshow({
		idx: idx(),
		setIdx: setIdx,
		length: props.content.images.length,
		speed: props.content.speed,
	});

	return (
		<>
			<div
				class={cn(
					'relative h-80 max-h-180 min-h-50 w-full contain-paint sm:h-[60vh] sm:min-h-120',
					imageRoundedVariants({ pos: 'right' }),
				)}
			>
				<For each={props.content.images}>
					{(image, i) => (
						<Image
							class="absolute inset-0"
							active={i() === idx()}
							anim="fade"
							image={image}
							widths={[400, 650, 1400]}
						/>
					)}
				</For>
			</div>

			<SlideNav
				class="2xl:w-diff my-3 sm:mb-0 2xl:mt-0 flex-col sm:flex-row 2xl:flex-col"
				idx={idx()}
				setIdx={setIdx}
				length={props.content.images.length}
			/>
		</>
	);
}

// src/components/sections/Hero.svelte
<script lang="ts">
  import { modals } from "~/frontend/stores";
  import { headingStyles, descStyles, imageStyles } from "./styles";
  import Slidenav from "@actions/Slidenav.svelte";

  import { type PropsOf } from "./registry";
  import { actionStyles } from "@actions/styles";
  let { meta }: { meta: PropsOf<"Hero"> } = $props();
  let idx = $state(0);
</script>

{#snippet imageCarousel()}
  {#each meta.content as image, i}
    <img
      class={imageStyles({ anim: "grow", active: idx == i })}
      fetchpriority={i === idx ? "low" : "high"}
      alt={image.alt}
      {...image.meta}
    />
  {/each}
{/snippet}

<div
  class="hidden w-1/2 flex-none flex-col items-center gap-6 sm:flex 2xl:flex-row-reverse"
>
  <div
    class="flex h-[70vh] max-h-165 min-h-100 justify-evenly rounded-sm contain-paint"
  >
    {@render imageCarousel()}
  </div>

  <div class="gap-5 flex 2xl:flex-col">
    <Slidenav bind:idx length={meta.content.length}></Slidenav>
  </div>
</div>

<div class="relative">
  <h1 class={headingStyles({ size: "6xl" })}>
    {meta.title}
  </h1>

  <div class="my-5 flex items-center gap-5 sm:hidden">
    <div
      class="-ml-inset flex h-60 flex-1 justify-evenly contain-paint"
    >
      {@render imageCarousel()}
    </div>

    <div class="flex flex-col gap-5">
      <Slidenav bind:idx length={meta.content.length} />
    </div>
  </div>

  <p class="{descStyles({ size: 'base' })} mt-3">
    {meta.desc}
  </p>

  <div class="mt-9">
    <button class={actionStyles()} onclick={() => modals.open(modals.talk)}
      >Let's Talk</button
    >
  </div>
</div>
