// src/components/decor/FluidTalk.svelte
<script lang="ts">
  import { modals } from "@/frontend/stores.svelte";
  import { useQueryDevice } from "@/frontend/mobile.svelte";
  import Mailbox from "@/icons/ph/mailbox-fill.svelte";
  import { actionStyles, pillSize } from "@/components/actions/styles";
  import { onMount } from "svelte";

  let sensor: HTMLElement;
  let above: boolean = $state(true);
  let style: null | string = $state(null);
  let hydrated: boolean = $state(false);
  let transitioning: boolean = false;

  const phone = useQueryDevice(1000);
  const inset = $derived(phone.isMobile ? 10 : 50);

  onMount(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        const outside = !(entry.intersectionRatio < 1.0);
        if (outside != (above && entry.boundingClientRect.top < 0)) {
          above = outside;
          update();
        }
      },
      { threshold: [0, 1.0] },
    );

    setTimeout(() => {
      hydrated = true;
    }, 20);

    observer.observe(sensor);
    const resizeObserver = new ResizeObserver(() => {
      update();
    });
    resizeObserver.observe(document.documentElement);
  });

  const update = () => {
    if (!above) {
      if (transitioning) return;
      const r = sensor.getBoundingClientRect();
      style = `${window.innerWidth - r.x - pillSize - inset}px calc(100svh - ${pillSize + inset}px) 0 `;
    } else {
      style = null;
    }
  };
</script>

<div class="relative mt-9 h-14 xl:h-16" bind:this={sensor}>
  <button
    aria-label="Let's talk (Ctrl+/)"
    class="z-1 {above
      ? `${actionStyles()} absolute h-14 w-34 xl:h-16 xl:w-42`
      : `${actionStyles({ variant: 'pill', background: 'accent' })} fixed top-0 `}"
    class:duration-1000={hydrated}
    style="translate: {style}; transition-property: width, height, border-radius, translate, background-color, color; will-change: width, height, border-radius, translate, background-color, color"
    onclick={() => modals.open(modals.talk)}
  >
    <div
      aria-hidden="true"
      class="absolute top-1/2 left-1/2 -translate-1/2 whitespace-nowrap transition-opacity duration-500 {above
        ? 'opacity-100'
        : 'opacity-0'}"
    >
      Let's Talk
    </div>

    <Mailbox
      class="absolute top-1/2 left-1/2 size-11 -translate-1/2 transition-opacity duration-500 {above
        ? 'opacity-0'
        : 'opacity-100'}"
    />
  </button>
</div>

// src/components/FluidTalk.tsx
import { createSignal, onMount, onCleanup } from 'solid-js';
import { modals } from '@/frontend/stores';
import { useQueryDevice } from '@/frontend/mobile';
import Mailbox from '~icons/ph/mailbox-fill';
import { buttonVariants, fabVariants, fabSize } from '@/components/Actions';
import { cn } from '@/frontend/utils';

export default function FluidTalk() {
	let sensor: HTMLElement;
	const [above, setAbove] = createSignal(true);
	const [style, setStyle] = createSignal<string | null>(null);
	const phone = useQueryDevice(1000);
	const inset = () => (phone.isMobile() ? 25 : 70);

	const update = () => {
		if (above() || !sensor) return setStyle(null);
		const { x } = sensor.getBoundingClientRect();
		setStyle(
			`${window.innerWidth - x - fabSize - inset()}px calc(100svh - ${fabSize + inset()}px) 0`,
		);
	};

	onMount(() => {
		const observer = new IntersectionObserver(
			([entry]) => {
				if (!entry) return;
				const nextAbove = !(entry.intersectionRatio < 1);
				if (nextAbove != (above() && entry.boundingClientRect.top < 0)) {
					setAbove(nextAbove);
					update();
				}
			},
			{ threshold: [0, 1] },
		);
		observer.observe(sensor);

		const resize = new ResizeObserver(() => update());
		resize.observe(document.documentElement);

		window.addEventListener('resize', update, { passive: true });

		onCleanup(() => {
			observer.disconnect();
			resize.disconnect();
			window.removeEventListener('resize', update);
		});
	});

	return (
		<div class="relative mt-9 h-14 xl:h-16" ref={(el) => (sensor = el!)}>
			<button
				aria-label="Let's talk (Ctrl+/)"
				class={cn(
					'z-1 duration-1000',
					above()
						? cn(buttonVariants(), 'absolute h-14 w-34 xl:h-16 xl:w-42')
						: cn(fabVariants({ variant: 'pill', background: 'accent' }), 'fixed top-0'),
				)}
				style={{
					translate: style() ?? undefined,
					'transition-property': 'width, height, border-radius, translate, background-color, color',
					'will-change': 'width, height, border-radius, translate, background-color, color',
				}}
				onClick={() => modals.open(modals.talk)}
			>
				<div
					aria-hidden="true"
					class={cn(
						'absolute top-1/2 left-1/2 -translate-1/2 whitespace-nowrap transition-opacity duration-500',
						above() ? 'opacity-100' : 'opacity-0',
					)}
				>
					Let's Talk
				</div>
				<Mailbox
					class={cn(
						'absolute top-1/2 left-1/2 size-10 sm:size-12 -translate-1/2 transition-opacity duration-500',
						above() ? 'opacity-0' : 'opacity-100',
					)}
				/>
			</button>
		</div>
	);
}
