// src/components/interact/modals/Menus.svelte
<script>
  import Modal from "@modals/Modal.svelte";
  import Form from "@modals/Form.svelte";
  import Input from "@fields/Input.svelte";
  import Select from "@fields/Select.svelte";
  import Photos from "@fields/Photos.svelte";
  import TextArea from "@fields/TextArea.svelte";
  import PhoneNumber from "@fields/PhoneNumber.svelte";
  import StarSlider from "@fields/StarSlider.svelte";

  import { modals, genUid } from "~/frontend/stores.svelte";
  import { modalStyles } from "./styles";
  import business from "@root/content/business.json";
  import { actionStyles } from "@actions/styles";

  const talkUid = genUid();
  let talkModal = $derived(modals.is(modals.talk));
  const reviewUid = genUid();
  let reviewModal = $derived(modals.is(modals.review));
</script>

<svelte:window
  onkeydown={(e) => {
    if (e.ctrlKey && e.key === "/") {
      e.preventDefault();
      modals.open(modals.talk);
    }
  }}
/>

<Modal
  bind:open={talkModal}
  uid={talkUid}
  class={modalStyles({ background: "blur", overlay: true, open: talkModal })}
>
  <Form
    action="/submissions/talk"
    name="contact"
    title="Let's talk"
    id={talkUid}
    class="space-y-8"
  >
    <p class="mt-2 desc-sm">
      Feel free to ask a question and/or quote.
    </p>

    <Input name="E-mail" required type="email" autocomplete="email" validate />
    <PhoneNumber validate></PhoneNumber>
    <Select
      name="Location"
      values={["Select a location", ...business.areaServed]}
    />
    <TextArea required minlength="14" name="Message" />
    <Photos />
    <button
      value="submit"
      class={actionStyles({ display: "fill", background: "fill" })}
    >
      Submit
    </button>
  </Form>
</Modal>

<Modal
  bind:open={reviewModal}
  uid={reviewUid}
  class={modalStyles({ background: "blur", overlay: true, open: reviewModal })}
>
  <Form
    action="/submissions/review"
    name="review"
    title="Write a review"
    id={reviewUid}
    class="space-y-4"
  >
    <p class="mt-2 desc-sm italic">*We will verify your submission via email.</p>

    <StarSlider />
    <Input name="Full name" required type="name" autocomplete="name" />
    <Input name="E-mail" required type="email" autocomplete="email" validate />
    <Select
      name="Location"
      values={["Select a location", ...business.areaServed]}
      required
    />

    <TextArea required minlength="25" name="Review" />

    <button
      value="submit"
      class={actionStyles({ display: "fill", background: "fill" })}
    >
      Submit
    </button>
  </Form>
</Modal>

// src/components/Menus.tsx
import Dialog from '@corvu/dialog';
import type { ComponentProps, JSX } from 'solid-js';
import { Show } from 'solid-js';
import createPersistent from 'solid-persistent';
import Inputs from '@/components/Inputs';
import Actions from '@/components/Actions';
import X from '~icons/ph/x-bold';
import business from '#/business.json';

function LetsTalk(props: { children: JSX.Element } & ComponentProps<'button'>) {
	const persistedContent = createPersistent(() => {
		return (
			<div class="mt-12 space-y-11">
				<Inputs.Email required />
				<Inputs.PhoneNumber validate />
				<Inputs.Select name="Location" items={["Select a location", ...business.areaServed]} />
				<Inputs.TextArea name="Messege" />
				<Inputs.Photos />
				<Actions.Button variant="fill">Submit</Actions.Button>
			</div>
		);
	});

	return (
		<Dialog>
			<Dialog.Trigger {...props}>{props.children}</Dialog.Trigger>
			<Dialog.Portal>
				<Dialog.Overlay class="data-open:animate-in data-open:fade-in-0% data-closed:animate-out data-closed:fade-out-0% fixed inset-0 z-4 bg-white/40 backdrop-blur-2xl" />
				<Dialog.Content class="data-open:animate-in data-open:zoom-in-98% data-closed:fade-out-0% data-open:fade-in-0% data-closed:animate-out data-closed:zoom-out-98% fixed inset-0 z-4 overflow-y-scroll">
					<div class="relative mx-auto w-full max-w-120 bg-white p-10 sm:my-10 sm:rounded-md">
						<Form title="Let's talk" desc="Feel free to ask a question and a quote." name="contact">
							{persistedContent()}
						</Form>
					</div>
				</Dialog.Content>
			</Dialog.Portal>
		</Dialog>
	);
}

function Form(props: {
	title: string;
	name: string;
	desc?: string;
	action?: string;
	children?: JSX.Element;
}) {
	return (
		<>
			<div class="gap-3 flex items-center">
				<Dialog.Label class="flex-1 font-serif text-5xl font-bold lg:text-6xl">
					{props.title}
				</Dialog.Label>

				<Dialog.Close type="button" class="bg-tone cursor-pointer rounded-[50%] p-2" tabIndex={0}>
					<X class="size-10 rounded-[50%] lg:w-11" />
				</Dialog.Close>
			</div>

			<Show when={props.desc}>
				<Dialog.Description class="mt-3 text-base">{props.desc}</Dialog.Description>
			</Show>

			<form
				name={props.name}
				action={props.action}
				enctype="multipart/form-data"
				method="post"
				data-netlify
			>
				<input type="hidden" name="form-name" value={props.name} />
				{props.children}
			</form>
		</>
	);
}

const Menus = { LetsTalk };
export default Menus;
