// src/components/Video.tsx
import { onMount, onCleanup, createEffect } from 'solid-js';
import { videoPlaying, setVideoPlaying } from '@/frontend/stores';

export default function Video(props: { poster: string; url: string }) {
	let node: HTMLVideoElement | undefined;

	createEffect(() => {
		if (!videoPlaying() && node && !node.paused) {
			node.pause();
		}
	});

	onMount(() => {
		if (!node) return;

		const observer = new IntersectionObserver(([entry]) => {
			if (entry && entry.isIntersecting === false) {
				setVideoPlaying(false);
			}
		});
		observer.observe(node);

		onCleanup(() => {
			observer.disconnect();
		});
	});

	return (
		<video
			ref={node}
			poster={props.poster}
			preload="none"
			class="absolute h-full w-full cursor-pointer object-cover"
			controls
			onPlay={() => setVideoPlaying(true)}
			onPause={() => setVideoPlaying(false)}
			onEnded={() => setVideoPlaying(false)}
		>
			<source src={props.url} />
			Your browser does not support the video tag.
		</video>
	);
}

// src/components/Video.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { videoPlaying } from "@/frontend/stores.svelte";

  let node: HTMLVideoElement;
  const { poster, url }: { poster: string; url: string } = $props();

  onMount(() => {
    const unsub = videoPlaying.subscribe((playing) => {
      if (!playing && !node.paused) {
        node.pause();
      }
    });

    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting == false) {
        videoPlaying.set(false);
      }
    });

    observer.observe(node);

    return () => {
      unsub();
      observer.disconnect();
    };
  });
</script>

<video
  bind:this={node}
  {poster}
  loading="lazy"
  preload="none"
  class="absolute h-full w-full cursor-pointer object-cover"
  controls
  onplay={() => videoPlaying.set(true)}
  onpause={() => videoPlaying.set(false)}
  onended={() => videoPlaying.set(false)}
>
  <source src={url} />
  Your browser does not support the video tag.
</video>
