// src/components/sections/Cardshow.svelte
<script lang="ts">
  import Slidenav from "@actions/Slidenav.svelte";

  import { type SubPropsOf } from "./registry";
  import { actionStyles } from "@actions/styles";
  const { meta }: { meta: SubPropsOf<"Cardshow", "content"> } = $props();
  let idx = $state(0);
</script>

<div class="2xl:max-w-inner bg-accent flex rounded-sm contain-paint">
  {#each meta as card, i}
    <div
      class="sm:px-auto flex w-full flex-shrink-0 flex-col items-center justify-center px-5 py-8 transition-opacity duration-800 sm:flex-row sm:gap-8 sm:px-0 sm:py-0
      {i == idx ? '' : 'pointer-events-none opacity-0'}"
      inert={i != idx}
      style="transform: translateX(-{i * 100}%)"
    >
      <div
        class="relative aspect-video w-full flex-none rounded-sm contain-paint sm:h-full sm:w-1/2 sm:rounded-none"
      >
        {#if card.media.type == "image"}
          <img
            class="absolute h-full w-full object-cover select-none"
            alt={card.media.alt}
            draggable={false}
            {...card.media.meta}
          />
        {:else if card.media.type == "video"}
          <video
            poster={card.media.poster.src}
            loading="lazy"
            preload="none"
            class="absolute h-full w-full cursor-pointer object-cover"
            controls
          >
            <source src={card.media.url} />
            Your browser does not support the video tag.
          </video>
        {:else if card.media.type == "yt-video"}
          <iframe
            loading="lazy"
            src={card.media.url}
            title="YouTube video player"
            class="absolute h-full w-full select-none"
            frameborder="0"
            allow="accelerometer; clipboard-write; encrypted-media; picture-in-picture"
            referrerpolicy="strict-origin-when-cross-origin"
            allowfullscreen
          ></iframe>
        {/if}
      </div>

      <div class="mt-6 sm:my-16 w-full">
        <h3 class="heading-4xl mb-1">{card.title}</h3>
        <p class="desc-base">
          {card.desc}
        </p>

        {#if card.link}
          <div class="mt-7">
            <a
              rel="noopener noreferrer"
              class={actionStyles()}
              target="_blank"
              href={card.link.url}>{card.link.name}</a
            >
          </div>
        {/if}
      </div>

      <div class="hidden sm:block"></div>
    </div>
  {/each}
</div>

<div class="flex justify-center gap-2 2xl:flex-col">
  <Slidenav length={meta.length} bind:idx />
</div>

// src/sections/Cardshow.tsx
import type { Props as CardshowMeta } from './Cardshow.astro';

import { createSignal, For, Show } from 'solid-js';
import Image from '@/components/Image';
import SlideNav from '@/components/SlideNav';
import YoutubeVideo from '@/components/YoutubeVideo';
import Video from '@/components/Video';
import { Link } from '@/components/Actions';
import { slideshow } from '@/frontend/slideshow';
import { cn } from '@/frontend/utils';

export default function Cardshow(props: { meta: CardshowMeta['content']; speed: number }) {
	const [idx, setIdx] = createSignal(0);

	slideshow({
		idx: idx(),
		setIdx: setIdx,
		length: props.meta.length,
		speed: props.speed,
	});

	return (
		<>
			<div class="2xl:w-diff flex-shrink-0" />
			<div class="bg-accent flex rounded-md contain-paint">
				<For each={props.meta}>
					{(card, i) => {
						const isActive = () => i() === idx();
						return (
							<div
								class={cn(
									'sm:px-auto flex min-w-full flex-col items-center justify-center gap-6 px-5 py-8 transition-opacity duration-800 sm:flex-row sm:gap-8 sm:px-0 sm:py-0',
									!isActive() ? 'pointer-events-none opacity-0' : '',
								)}
								inert={!isActive()}
								style={{ translate: `-${i() * 100}% 0` }}
							>
								<div class="relative w-full flex-shrink-0 rounded-sm contain-paint sm:h-full sm:w-1/2 sm:rounded-none aspect-video">
									{(() => {
										switch (card.media.type) {
											case 'image':
												return <Image image={card.media.image} widths={[400, 650, 1300]} />;
											case 'video':
												return <Video poster={card.media.image.src.src} url={card.media.url} />;
											case 'yt-video':
												return <YoutubeVideo id={card.media.id} />;
										}
									})()}
								</div>

								<div class="w-full sm:my-10">
									<h3 class="heading-4xl mb-1">{card.title}</h3>
									<p class="desc-base">{card.desc}</p>

									<Show when={card.link}>
										{(link) => (
											<div class="mt-7">
												<Link rel="noopener noreferrer" target="_blank" href={link().url}>
													{link().name}
												</Link>
											</div>
										)}
									</Show>
								</div>

								<div class="hidden sm:block" />
							</div>
						);
					}}
				</For>
			</div>

			<SlideNav
				class="mt-3 2xl:mt-0 2xl:flex-col"
				idx={idx()}
				setIdx={setIdx}
				length={props.meta.length}
			/>
		</>
	);
}
