// src/components/sections/Faq.svelte
<script lang="ts">
  import { slide } from "svelte/transition";

  import { type PropsOf } from "./registry";
  import { quadOut } from "svelte/easing";
  const { meta }: { meta: PropsOf<"Faq"> } = $props();

  let active: null | number = $state(null);

  function slideWithScroll(node: HTMLElement, { duration = 1000 }) {
    const r = node.getBoundingClientRect();
    if (r.top < 0) {
      window.scrollTo({
        top: window.scrollY + r.top,
        behavior: "smooth",
      });
    }
    return {
      ...slide(node, { duration, easing: quadOut }),
      tick: (t: any) => {},
    };
  }
</script>

<div class="-mt-6">
  {#each meta.content as faq, i}
    {@const open = i == active}

    <button
      class="border-accent w-full cursor-pointer touch-manipulation border-t-1 py-8 first:border-t-0"
      onclick={() => {
        active = open ? null : i;
        window.getSelection()?.removeAllRanges();
      }}
    >
      <div class="gap-inset flex items-center justify-between">
        <h3 class="heading-3xl">{faq.title}</h3>
        <div
          class="expand relative size-6 gap-4 flex-none{i === active
            ? ' open'
            : ''}"
        ></div>
      </div>

      {#if open}
        <div
          transition:slideWithScroll={{ duration: 350 }}
          class="prose mt-3 mr-4 max-w-[110ch] font-sans"
        >
          {@html faq.desc}
        </div>
      {/if}
    </button>
  {/each}
</div>

<style lang="scss">
  .expand {
    &::before {
      content: "";
      position: absolute;
      top: 0;
      left: calc(50% - 1px);
      bottom: 0;
      width: 2px;
      background-color: var(--color-black);
      transform-origin: center;
      transition: transform 250ms;
    }
    &::after {
      content: "";
      position: absolute;
      left: 0;
      top: calc(50% - 1px);
      right: 0;
      height: 2px;
      background-color: var(--color-black);
      transform-origin: center;
    }
    &.open::before {
      transform: rotateZ(90deg);
    }
  }
</style>

// src/sections/Faq.tsx
import { For } from 'solid-js';
import type { Props as FaqMeta } from './Faq.astro';
import Accordion from '@corvu/accordion';
import styles from './Faq.module.scss';
import { cn } from '@/frontend/utils';

export default function Faq(props: { content: FaqMeta['content'] }) {
	return (
		<div class="-mt-6">
			<Accordion collapseBehavior="hide">
				<For each={props.content}>
					{(faq) => {
						return (
							<div class="border-accent border-t-1 py-8 first:border-t-0">
								<Accordion.Item>
									<h3 class="heading-3xl">
										<Accordion.Trigger
											class={cn(
												'gap-inset flex w-full cursor-pointer touch-manipulation items-center justify-between',
												styles.trigger,
											)}
										>
											{faq.title}
											<div
												class={cn('relative size-6 flex-none gap-4', styles.expand)}
												aria-hidden="true"
											/>
										</Accordion.Trigger>
									</h3>

									<Accordion.Content class={cn('contain-paint', styles.content)}>
										{/* eslint-disable-next-line solid/no-innerhtml */}
										<div class="prose my-3 mr-4 max-w-[110ch] font-sans" innerHTML={faq.desc} />
									</Accordion.Content>
								</Accordion.Item>
							</div>
						);
					}}
				</For>
			</Accordion>
		</div>
	);
}
