// src/components/sections/Header.svelte
<script lang="ts">
  import Modal from "@/components/modals/Modal.svelte";
  import Burger from "@/components/decor/Burger.svelte";
  import { modals, genUid } from "@/frontend/stores.svelte";

  let open = $derived(modals.is(modals.mobile));
  const uid = genUid();

  import { modalStyles } from "@/components/modals/styles";
  import { type PropsOf } from "@/components/registry";
  const { meta }: { meta: PropsOf<"Header"> } = $props();
</script>

<ul class="mt-1 hidden gap-14 md:flex">
  {#each meta.content as item}
    <li>
      <a href="#{item.id}" class="desc-sm c relative" tabindex="0">
        {item.name}
      </a>
    </li>
  {/each}
</ul>

<button
  aria-label="Open mobile menu"
  class="relative z-1 size-10 cursor-pointer touch-manipulation md:hidden"
  data-include-in-focuslock
  tabindex="0"
  onclick={() => {
    document.body.scrollTop = document.documentElement.scrollTop = 1;
    modals.toggle(modals.mobile);
  }}
>
  <Burger bind:open />
</button>

<Modal class={modalStyles({ open })} {uid} bind:open>
  <ul class="px-inset flex h-full flex-col items-start justify-center gap-6">
    {#each meta.content as item}
      <li>
        <a
          href={`#${item.id}`}
          onclick={(_) => {
            modals.close();
          }}
          tabindex="0"
          class="heading-2xl leading-none"
        >
          {item.name}
        </a>
      </li>
    {/each}
  </ul>
</Modal>

<style>
  .c {
    &::after {
      content: "";
      position: absolute;
      bottom: -0.4rem;
      right: 10%;
      left: 10%;
      transform: scaleX(0);
      height: 1px;
      background: var(--color-black);
      transition: transform 200ms ease-in-out;
      opacity: 0.5;
    }
    &:hover::after {
      transform: scaleX(1);
    }
  }
</style>

// src/sections/Header.tsx
import { createEffect, For } from 'solid-js';
import type { Props as HeaderMeta } from './Header.astro';
import styles from './Header.module.scss';
import { cn } from '@/frontend/utils';
import Dialog from '@corvu/dialog';

export default function Header(props: { content: HeaderMeta['content'] }) {
	return (
		<Dialog>
			{(popover) => {
				createEffect(() => {
					if (popover.open) {
						document.body.scrollTop = document.documentElement.scrollTop = 1;
					}
				});
				return (
					<>
						<Dialog.Trigger
							class={cn(
								'z-2 size-10 cursor-pointer touch-manipulation text-neutral-950',
								styles.burger,
							)}
							aria-label="mobile menu"
						/>
						<Dialog.Content
							class={cn(
								'data-open:animate-in data-closed:fade-out-0% data-open:fade-in-0% data-closed:animate-out sm:data-open:zoom-in-80% sm:data-closed:zoom-out-80%',
								'border-primary-dark fixed top-20 right-0 bottom-0 left-0 z-2 flex flex-col justify-center gap-7 bg-white p-9 sm:absolute sm:inset-auto sm:right-0 sm:top-full sm:translate-y-4 sm:rounded-xl sm:border-2',
							)}
						>
							<ul class="contents">
								<For
									each={props.content}
									children={(item, index) => (
										<li
											class="animate-in [animation-fill-mode:backwards]"
											style={{
												'--tw-enter-translate-x': '-5rem',
												'animation-delay': `${index() * 150}ms`,
											}}
										>
											<a
												class={cn(styles.link, 'font-serif text-3xl font-semibold')}
												href={`#${item.id}`}
												tabindex="0"
												onClick={() => popover.setOpen(false)}
											>
												{item.name}
											</a>
										</li>
									)}
								/>
							</ul>
						</Dialog.Content>
					</>
				);
			}}
		</Dialog>
	);
}
